name: Benchmarking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v5

      - name: cache and/or reuse compiled Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: build and run benchmarks
        run: cargo bench --verbose
